[toolchain]

[features]
seeds = false
skip-lint = false

[programs.mainnet]
crewmate = "s1xY9GbteSddorsie2y265Qg56QXa45C6NVAaxb56wV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
