[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
crewmate = "s1xVDPnBMJ2pAjZ2t2ijnz27BJzRbySxb9eWx6wT9cV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
